// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0YuoyLU2HAesAkmA3VGGVE_GCYqZfJdM',
    appId: '1:446830379713:web:9e2aba3987efa9ccc70a40',
    messagingSenderId: '446830379713',
    projectId: 'gather-circle',
    authDomain: 'gather-circle.firebaseapp.com',
    storageBucket: 'gather-circle.firebasestorage.app',
    measurementId: 'G-2WJGNB0MJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkNpzyFllNp5TVCxUrOUk7SiqpQiAgdfc',
    appId: '1:446830379713:android:25c20de9c02fc9d6c70a40',
    messagingSenderId: '446830379713',
    projectId: 'gather-circle',
    storageBucket: 'gather-circle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9auBGmU_q5uKqh7urjadHm-HFnzKAOwU',
    appId: '1:446830379713:ios:3aca5bc3d987876cc70a40',
    messagingSenderId: '446830379713',
    projectId: 'gather-circle',
    storageBucket: 'gather-circle.firebasestorage.app',
    iosBundleId: 'com.example.gatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9auBGmU_q5uKqh7urjadHm-HFnzKAOwU',
    appId: '1:446830379713:ios:3aca5bc3d987876cc70a40',
    messagingSenderId: '446830379713',
    projectId: 'gather-circle',
    storageBucket: 'gather-circle.firebasestorage.app',
    iosBundleId: 'com.example.gatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0YuoyLU2HAesAkmA3VGGVE_GCYqZfJdM',
    appId: '1:446830379713:web:85621ecb0dca6cfec70a40',
    messagingSenderId: '446830379713',
    projectId: 'gather-circle',
    authDomain: 'gather-circle.firebaseapp.com',
    storageBucket: 'gather-circle.firebasestorage.app',
    measurementId: 'G-4ZNGWES8X6',
  );
}
